apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    commit.image.appsody.dev/author: dannil@dk.ibm.com <danniluong@gmail.com>
    commit.image.appsody.dev/committer: dannil@dk.ibm.com <danniluong@gmail.com>
    commit.image.appsody.dev/contextDir: C:\danni-springboot2
    commit.image.appsody.dev/date: Mon Dec 2 11:09:09 2019 +0100
    commit.image.appsody.dev/message: "20191201"
    image.opencontainers.org/created: "2019-12-04T21:52:32+01:00"
    image.opencontainers.org/documentation: https://github.com/danniluong/danni-springboot2
    image.opencontainers.org/revision: 7ee5781d6ef4f0897c4c6e496631727d4e87cfd6
    image.opencontainers.org/source: |
      https://github.com/danniluong/danni-springboot2/tree/master
    image.opencontainers.org/url: https://github.com/danniluong/danni-springboot2
    stack.appsody.dev/authors: Erin Schnabel <schnabel@us.ibm.com>, Ozzy <ozzy@ca.ibm.com>
    stack.appsody.dev/configured: appsody/java-spring-boot2:0.3
    stack.appsody.dev/created: "2019-12-03T16:32:12Z"
    stack.appsody.dev/description: Spring Boot using OpenJ9 and Maven
    stack.appsody.dev/licenses: Apache-2.0
    stack.appsody.dev/tag: appsody/java-spring-boot2:0.3.19
    stack.appsody.dev/title: Spring Boot®
  creationTimestamp: null
  labels:
    image.opencontainers.org/title: danni-springboot2
    stack.appsody.dev/id: java-spring-boot2
    stack.appsody.dev/version: 0.3.19
  name: danni-springboot2
  namespace: danskebank
spec:
  applicationImage: dev.local/danni-springboot2
  createKnativeService: false
  expose: true
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /actuator/liveness
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 2
  monitoring:
    endpoints:
    - path: /actuator/prometheus
    labels:
      k8s-app: danni-springboot2
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 2
    timeoutSeconds: 1
  service:
    annotations:
      prometheus.io/path: /actuator/prometheus
      prometheus.io/scrape: "true"
    port: 8080
    type: NodePort
  stack: java-spring-boot2
  version: 1.0.0
status: {}